var searchData=
[
  ['a_20derivative_0',['Obtaining a Derivative',['../flx_methods.html',1,'background']]],
  ['a_20derivative_1',['Carrying a derivative',['../flx_derivation.html#flx_carry',1,'']]],
  ['a_20loop_2',['Differentiating through a loop',['../flx_examples.html#flx_ex_loop',1,'']]],
  ['a_20point_3',['Derivative at a point',['../flx_derivation.html#flx_derivative',1,'']]],
  ['a_20program_4',['Differentiating a Program',['../flx_derivation.html',1,'background']]],
  ['a_20result_5',['Reading a result',['../flx_seeding.html#flx_landing',1,'']]],
  ['algebra_6',['Algebra',['../flx_glossary.html#flx_gl_algebra',1,'Algebra'],['../flx_algebra.html',1,'Hyperdual Algebra']]],
  ['an_20order_7',['Cost of an order',['../flx_seeding.html#flx_cost',1,'']]],
  ['and_20inverse_8',['Sum, product, and inverse',['../flx_algebra.html#flx_arithmetic',1,'']]],
  ['and_20mixed_20derivative_9',['Gradient and mixed derivative',['../flx_examples.html#flx_ex_gradient',1,'']]],
  ['and_20reading_10',['Seeding and Reading',['../flx_seeding.html',1,'background']]],
  ['and_20several_20arguments_11',['Higher orders, and several arguments',['../flx_derivation.html#flx_higher',1,'']]],
  ['and_20variables_12',['Constants and variables',['../flx_algebra.html#flx_constants',1,'']]],
  ['arguments_13',['arguments',['../flx_seeding.html#flx_assignment',1,'Assigning units to arguments'],['../flx_derivation.html#flx_higher',1,'Higher orders, and several arguments']]],
  ['arithmetic_14',['Floating-point arithmetic',['../flx_glossary.html#flx_gl_float',1,'']]],
  ['arrays_15',['Structure of arrays',['../flx_glossary.html#autotoc_md6',1,'']]],
  ['as_20compositions_16',['Programs as compositions',['../flx_derivation.html#flx_program',1,'']]],
  ['as_20prefixes_17',['Lower orders as prefixes',['../flx_algebra.html#flx_subalgebra',1,'']]],
  ['as_5fbase_18',['as_base',['../structflx_1_1as__base.html',1,'flx']]],
  ['as_5fbase_5ftype_5ft_19',['as_base_type_t',['../group__traits_ga8176776e24a43e80799f1a10067b6eb2.html#ga8176776e24a43e80799f1a10067b6eb2',1,'flx']]],
  ['as_5fhyperdual_5flike_20',['as_hyperdual_like',['../structflx_1_1as__hyperdual__like.html',1,'flx']]],
  ['as_5fhyperdual_5flike_3c_20t_2c_20kumi_3a_3aapply_5ftraits_5ft_3c_20as_5fhyperdual_5flike_2c_20ts_20_3e_20_3e_21',['as_hyperdual_like&lt; T, kumi::apply_traits_t&lt; as_hyperdual_like, Ts &gt; &gt;',['../structflx_1_1as__hyperdual__like.html',1,'flx']]],
  ['as_5fhyperdual_5fn_5ft_22',['as_hyperdual_n_t',['../group__traits_ga168201d3b044c23a8d7073628fa779ac.html#ga168201d3b044c23a8d7073628fa779ac',1,'flx']]],
  ['as_5fhyperdual_5ft_23',['as_hyperdual_t',['../group__traits_gaac44af756975dec034912c4d9b007dc9.html#gaac44af756975dec034912c4d9b007dc9',1,'flx']]],
  ['as_5fvar_24',['as_var',['../structflx_1_1as__var.html',1,'flx']]],
  ['assigning_20units_20to_20arguments_25',['Assigning units to arguments',['../flx_seeding.html#flx_assignment',1,'']]],
  ['at_20a_20point_26',['Derivative at a point',['../flx_derivation.html#flx_derivative',1,'']]],
  ['at_20once_27',['at once',['../flx_examples.html#flx_ex_wide',1,'Several points at once'],['../flx_seeding.html#flx_wide',1,'Several points at once']]],
  ['automatic_20differentiation_28',['Automatic differentiation',['../flx_glossary.html#flx_gl_ad',1,'Automatic differentiation'],['../flx_methods.html#flx_automatic',1,'Automatic differentiation']]]
];
