var searchData=
[
  ['a_20derivative_0',['Obtaining a Derivative',['../flx_methods.html',1,'background']]],
  ['a_20derivative_1',['Carrying a derivative',['../flx_derivation.html#flx_carry',1,'']]],
  ['a_20loop_2',['Differentiating through a loop',['../flx_examples.html#flx_ex_loop',1,'']]],
  ['a_20point_3',['Derivative at a point',['../flx_derivation.html#flx_derivative',1,'']]],
  ['a_20program_4',['Differentiating a Program',['../flx_derivation.html',1,'background']]],
  ['a_20result_5',['Reading a result',['../flx_seeding.html#flx_landing',1,'']]],
  ['algebra_6',['Algebra',['../flx_glossary.html#flx_gl_algebra',1,'Algebra'],['../flx_algebra.html',1,'Hyperdual Algebra']]],
  ['an_20order_7',['Cost of an order',['../flx_seeding.html#flx_cost',1,'']]],
  ['and_20inverse_8',['Sum, product, and inverse',['../flx_algebra.html#flx_arithmetic',1,'']]],
  ['and_20mixed_20derivative_9',['Gradient and mixed derivative',['../flx_examples.html#flx_ex_gradient',1,'']]],
  ['and_20reading_10',['Seeding and Reading',['../flx_seeding.html',1,'background']]],
  ['and_20several_20arguments_11',['Higher orders, and several arguments',['../flx_derivation.html#flx_higher',1,'']]],
  ['and_20variables_12',['Constants and variables',['../flx_algebra.html#flx_constants',1,'']]],
  ['arguments_13',['arguments',['../flx_seeding.html#flx_assignment',1,'Assigning units to arguments'],['../flx_derivation.html#flx_higher',1,'Higher orders, and several arguments']]],
  ['arithmetic_14',['Floating-point arithmetic',['../flx_glossary.html#flx_gl_float',1,'']]],
  ['arrays_15',['Structure of arrays',['../flx_glossary.html#autotoc_md6',1,'']]],
  ['as_20compositions_16',['Programs as compositions',['../flx_derivation.html#flx_program',1,'']]],
  ['as_20prefixes_17',['Lower orders as prefixes',['../flx_algebra.html#flx_subalgebra',1,'']]],
  ['assigning_20units_20to_20arguments_18',['Assigning units to arguments',['../flx_seeding.html#flx_assignment',1,'']]],
  ['at_20a_20point_19',['Derivative at a point',['../flx_derivation.html#flx_derivative',1,'']]],
  ['at_20once_20',['at once',['../flx_examples.html#flx_ex_wide',1,'Several points at once'],['../flx_seeding.html#flx_wide',1,'Several points at once']]],
  ['automatic_20differentiation_21',['Automatic differentiation',['../flx_glossary.html#flx_gl_ad',1,'Automatic differentiation'],['../flx_methods.html#flx_automatic',1,'Automatic differentiation']]]
];
