# action.yml
name: 'Clone and Build Tests'
description: 'Clone and build a given repository'
inputs:
  options:  # compiler options
    description: 'Compiler options'
    required: false
    default: ''
  cmake-options:  # CMake options
    description: 'CMake options'
    required: false
    default: ''
  target:  # What to compile
    description: 'target'
    required: false
    default: 'unit'
  tests:  # What to test
    description: 'tests'
    required: false
    default: '^unit.*.exe'
  cpu:  # How much CPU do we use
    description: 'CPU Count'
    required: false
    default: '8'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.options }}
    - ${{ inputs.cmake-options }}
    - ${{ inputs.cpu }}
    - ${{ inputs.target }}
    - ${{ inputs.tests }}
