name: Fluxion CI
on:
  pull_request:
    branches:
      - main

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  derivative-clang:
    runs-on: [self-hosted]
    container:
      image: ghcr.io/jfalcou/compilers:v6
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { comp: clang_libcpp, arch: x86     , opts: -msse2    , target: derivative.exe, tests: ^derivative.*.exe }
        - { comp: clang       , arch: x86     , opts: -msse2    , target: derivative.exe, tests: ^derivative.*.exe }
        - { comp: clang       , arch: x86     , opts: -mavx2    , target: derivative.exe, tests: ^derivative.*.exe }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Prepare Fluxion with ${{ matrix.cfg.comp }} @ ${{ matrix.cfg.arch }} with ${{ matrix.cfg.opts }}
        run:  |
          mkdir build
          cd build
          cmake ..  -G Ninja -DFLUXION_OPTIONS="${{ matrix.cfg.opts }}" \
                    -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/${{ matrix.cfg.comp }}.${{ matrix.cfg.arch }}.cmake
      - name: Compile Unit Tests
        run:  |
          cd build
          ninja ${{ matrix.cfg.tests }} -j 8
      - name: Running Random Sampling Tests
        run:  |
          cd build
          ctest --output-on-failure -j 4 -R ${{ matrix.cfg.target }}

  forward_automatic-clang:
    runs-on: [self-hosted]
    container:
      image: ghcr.io/jfalcou/compilers:v6
    needs: derivative-clang
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { comp: clang_libcpp, arch: x86     , opts: -msse2    , target: forward_automatic.exe, tests: ^forward_automatic.*.exe }
        - { comp: clang       , arch: x86     , opts: -msse2    , target: forward_automatic.exe, tests: ^forward_automatic.*.exe }
        - { comp: clang       , arch: x86     , opts: -mavx2    , target: forward_automatic.exe, tests: ^forward_automatic.*.exe }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Prepare Fluxion with ${{ matrix.cfg.comp }} @ ${{ matrix.cfg.arch }} with ${{ matrix.cfg.opts }}
        run:  |
          mkdir build
          cd build
          cmake ..  -G Ninja -DFLUXION_OPTIONS="${{ matrix.cfg.opts }}" \
                    -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/${{ matrix.cfg.comp }}.${{ matrix.cfg.arch }}.cmake
      - name: Compile Unit Tests
        run:  |
          cd build
          ninja ${{ matrix.cfg.tests }} -j 8
      - name: Running Random Sampling Tests
        run:  |
          cd build
          ctest --output-on-failure -j 4 -R ${{ matrix.cfg.target }}

  derivative-gcc:
    runs-on: [self-hosted]
    container:
      image: ghcr.io/jfalcou/compilers:v6
    needs: forward_automatic-clang
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { comp: gcc         , arch: aarch64 , opts: -Wno-psabi, target: derivative.exe, tests: ^derivative.*.exe }
        - { comp: gcc         , arch: x86     , opts: -msse2    , target: derivative.exe, tests: ^derivative.*.exe }
        - { comp: gcc         , arch: x86     , opts: -mavx2    , target: derivative.exe, tests: ^derivative.*.exe }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Prepare Fluxion with ${{ matrix.cfg.comp }} @ ${{ matrix.cfg.arch }} with ${{ matrix.cfg.opts }}
        run:  |
          mkdir build
          cd build
          cmake ..  -G Ninja -DFLUXION_OPTIONS="${{ matrix.cfg.opts }}" \
                    -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/${{ matrix.cfg.comp }}.${{ matrix.cfg.arch }}.cmake
      - name: Compile Unit Tests
        run:  |
          cd build
          ninja ${{ matrix.cfg.tests }} -j 8
      - name: Running Random Sampling Tests
        run:  |
          cd build
          ctest --output-on-failure -j 4 -R ${{ matrix.cfg.target }}

  forward_automatic-gcc:
    runs-on: [self-hosted]
    container:
      image: ghcr.io/jfalcou/compilers:v6
    needs: derivative-gcc
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { comp: gcc         , arch: aarch64 , opts: -Wno-psabi, target: forward_automatic.exe, tests: ^forward_automatic.*.exe }
        - { comp: gcc         , arch: x86     , opts: -msse2    , target: forward_automatic.exe, tests: ^forward_automatic.*.exe }
        - { comp: gcc         , arch: x86     , opts: -mavx2    , target: forward_automatic.exe, tests: ^forward_automatic.*.exe }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Prepare Fluxion with ${{ matrix.cfg.comp }} @ ${{ matrix.cfg.arch }} with ${{ matrix.cfg.opts }}
        run:  |
          mkdir build
          cd build
          cmake ..  -G Ninja -DFLUXION_OPTIONS="${{ matrix.cfg.opts }}" \
                    -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/${{ matrix.cfg.comp }}.${{ matrix.cfg.arch }}.cmake
      - name: Compile Unit Tests
        run:  |
          cd build
          ninja ${{ matrix.cfg.tests }} -j 8
      - name: Running Random Sampling Tests
        run:  |
          cd build
          ctest --output-on-failure -j 4 -R ${{ matrix.cfg.target }}
