name: Fluxion CI
on:
  pull_request:
    branches:
      - main

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  derivative-clang:
    runs-on: [self-hosted]
    container:
      image: ghcr.io/jfalcou/compilers:v6
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { comp: clang_libcpp, arch: x86     , opts: -msse2    , target: derivative.exe, tests: ^derivative.*.exe }
        - { comp: clang       , arch: x86     , opts: -msse2    , target: derivative.exe, tests: ^derivative.*.exe }
        - { comp: clang       , arch: x86_asan, opts: -msse2    , target: derivative.exe, tests: ^derivative.*.exe }
        - { comp: clang       , arch: x86     , opts: -mavx2    , target: derivative.exe, tests: ^derivative.*.exe }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Testing Fluxion with ${{ matrix.cfg.comp }} on ${{ matrix.cfg.arch }} with ${{ matrix.cfg.opts }}
        uses: ./.github/actions/run_docker
        with:
          options:        '${{ matrix.cfg.opts }}'
          cmake-options:  '-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/${{ matrix.cfg.comp }}.${{ matrix.cfg.arch }}.cmake'
          target:         '${{ matrix.cfg.target }}'
          tests:          '${{ matrix.cfg.tests }}'
          cpu:            2

  forward_automatic-clang:
    runs-on: [self-hosted]
    container:
      image: ghcr.io/jfalcou/compilers:v6
    needs: derivative-clang
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { comp: clang_libcpp, arch: x86     , opts: -msse2    , target: forward_automatic.exe, tests: ^forward_automatic.*.exe }
        - { comp: clang       , arch: x86     , opts: -msse2    , target: forward_automatic.exe, tests: ^forward_automatic.*.exe }
        - { comp: clang       , arch: x86_asan, opts: -msse2    , target: forward_automatic.exe, tests: ^forward_automatic.*.exe }
        - { comp: clang       , arch: x86     , opts: -mavx2    , target: forward_automatic.exe, tests: ^forward_automatic.*.exe }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Testing Fluxion with ${{ matrix.cfg.comp }} on ${{ matrix.cfg.arch }} with ${{ matrix.cfg.opts }}
        uses: ./.github/actions/run_docker
        with:
          options:        '${{ matrix.cfg.opts }}'
          cmake-options:  '-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/${{ matrix.cfg.comp }}.${{ matrix.cfg.arch }}.cmake'
          target:         '${{ matrix.cfg.target }}'
          tests:          '${{ matrix.cfg.tests }}'
          cpu:            2

  derivative-gcc:
    runs-on: [self-hosted]
    container:
      image: ghcr.io/jfalcou/compilers:v6
    needs: forward_automatic-clang
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { comp: gcc         , arch: aarch64 , opts: -Wno-psabi, target: derivative.exe, tests: ^derivative.*.exe }
        - { comp: gcc         , arch: x86     , opts: -msse2    , target: derivative.exe, tests: ^derivative.*.exe }
        - { comp: gcc         , arch: x86     , opts: -mavx2    , target: derivative.exe, tests: ^derivative.*.exe }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Testing Fluxion with ${{ matrix.cfg.comp }} on ${{ matrix.cfg.arch }} with ${{ matrix.cfg.opts }}
        uses: ./.github/actions/run_docker
        with:
          options:        '${{ matrix.cfg.opts }}'
          cmake-options:  '-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/${{ matrix.cfg.comp }}.${{ matrix.cfg.arch }}.cmake'
          target:         '${{ matrix.cfg.target }}'
          tests:          '${{ matrix.cfg.tests }}'
          cpu:            2

  forward_automatic-gcc:
    runs-on: [self-hosted]
    container:
      image: ghcr.io/jfalcou/compilers:v6
    needs: derivative-gcc
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { comp: gcc         , arch: aarch64 , opts: -Wno-psabi, target: forward_automatic.exe, tests: ^forward_automatic.*.exe }
        - { comp: gcc         , arch: x86     , opts: -msse2    , target: forward_automatic.exe, tests: ^forward_automatic.*.exe }
        - { comp: gcc         , arch: x86     , opts: -mavx2    , target: forward_automatic.exe, tests: ^forward_automatic.*.exe }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Testing Fluxion with ${{ matrix.cfg.comp }} on ${{ matrix.cfg.arch }} with ${{ matrix.cfg.opts }}
        uses: ./.github/actions/run_docker
        with:
          options:        '${{ matrix.cfg.opts }}'
          cmake-options:  '-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/${{ matrix.cfg.comp }}.${{ matrix.cfg.arch }}.cmake'
          target:         '${{ matrix.cfg.target }}'
          tests:          '${{ matrix.cfg.tests }}'
          cpu:            2
