##==================================================================================================
## Fluxion - Post-Modern Automatic Derivation
## Copyright : Fluxion Project Contributors
## SPDX-License-Identifier: BSL-1.0
##==================================================================================================

##==================================================================================================
## module/derivative/core tests
##==================================================================================================
generate_test("unit/module/derivative/core/abs.cpp"                    )
generate_test("unit/module/derivative/core/absmax.cpp"                 )
generate_test("unit/module/derivative/core/absmin.cpp"                 )
generate_test("unit/module/derivative/core/add.cpp"                    )
generate_test("unit/module/derivative/core/average.cpp"                )
#generate_test("unit/module/derivative/core/binarize.cpp"               )
#generate_test("unit/module/derivative/core/binarize_not.cpp"           )
generate_test("unit/module/derivative/core/ceil.cpp"                   )
generate_test("unit/module/derivative/core/clamp.cpp"                  )
generate_test("unit/module/derivative/core/copysign.cpp"               )
generate_test("unit/module/derivative/core/dec.cpp"                    )
generate_test("unit/module/derivative/core/dist.cpp"                   )
generate_test("unit/module/derivative/core/div.cpp"                    )
generate_test("unit/module/derivative/core/fam.cpp"                    )
generate_test("unit/module/derivative/core/fanm.cpp"                   )
generate_test("unit/module/derivative/core/fdim.cpp"                   )
generate_test("unit/module/derivative/core/floor.cpp"                  )
generate_test("unit/module/derivative/core/fma.cpp"                    )
generate_test("unit/module/derivative/core/fms.cpp"                    )
generate_test("unit/module/derivative/core/fnma.cpp"                   )
generate_test("unit/module/derivative/core/fnms.cpp"                   )
generate_test("unit/module/derivative/core/frac.cpp"                   )
generate_test("unit/module/derivative/core/fsm.cpp"                    )
generate_test("unit/module/derivative/core/fsnm.cpp"                   )
generate_test("unit/module/derivative/core/inc.cpp"                    )
generate_test("unit/module/derivative/core/lerp.cpp"                   )
generate_test("unit/module/derivative/core/manhattan.cpp"              )
generate_test("unit/module/derivative/core/maxabs.cpp"                 )
generate_test("unit/module/derivative/core/max.cpp"                    )
generate_test("unit/module/derivative/core/maxmag.cpp"                 )
generate_test("unit/module/derivative/core/minabs.cpp"                 )
generate_test("unit/module/derivative/core/min.cpp"                    )
generate_test("unit/module/derivative/core/minmag.cpp"                 )
generate_test("unit/module/derivative/core/minus.cpp"                  )
generate_test("unit/module/derivative/core/mul.cpp"                    )
generate_test("unit/module/derivative/core/nearest.cpp"                )
generate_test("unit/module/derivative/core/negabsmax.cpp"              )
generate_test("unit/module/derivative/core/negabsmin.cpp"              )
generate_test("unit/module/derivative/core/negate.cpp"                 )
generate_test("unit/module/derivative/core/negatenz.cpp"               )
generate_test("unit/module/derivative/core/negmaxabs.cpp"              )
generate_test("unit/module/derivative/core/negminabs.cpp"              )
generate_test("unit/module/derivative/core/oneminus.cpp"               )
generate_test("unit/module/derivative/core/plus.cpp"                   )
generate_test("unit/module/derivative/core/rec.cpp"                    )
generate_test("unit/module/derivative/core/rem.cpp"                    )
generate_test("unit/module/derivative/core/round.cpp"                  )
generate_test("unit/module/derivative/core/rsqrt.cpp"                  )
generate_test("unit/module/derivative/core/sign.cpp"                   )
generate_test("unit/module/derivative/core/signnz.cpp"                 )
generate_test("unit/module/derivative/core/sqr_abs.cpp"                )
generate_test("unit/module/derivative/core/sqr.cpp"                    )
generate_test("unit/module/derivative/core/sqrt.cpp"                   )
generate_test("unit/module/derivative/core/sub.cpp"                    )
generate_test("unit/module/derivative/core/trunc.cpp"                  )

##==================================================================================================
## module/derivative/math tests
##==================================================================================================
generate_test("unit/module/derivative/math/acos.cpp"                  )
generate_test("unit/module/derivative/math/acosd.cpp"                 )
generate_test("unit/module/derivative/math/acosh.cpp"                 )
generate_test("unit/module/derivative/math/acospi.cpp"                )
generate_test("unit/module/derivative/math/acot.cpp"                  )
generate_test("unit/module/derivative/math/acotd.cpp"                 )
generate_test("unit/module/derivative/math/acoth.cpp"                 )
generate_test("unit/module/derivative/math/acotpi.cpp"                )
generate_test("unit/module/derivative/math/acsc.cpp"                  )
generate_test("unit/module/derivative/math/acscd.cpp"                 )
generate_test("unit/module/derivative/math/acsch.cpp"                 )
generate_test("unit/module/derivative/math/acscpi.cpp"                )
generate_test("unit/module/derivative/math/arg.cpp"                   )
generate_test("unit/module/derivative/math/asec.cpp"                  )
generate_test("unit/module/derivative/math/asecd.cpp"                 )
generate_test("unit/module/derivative/math/asech.cpp"                 )
generate_test("unit/module/derivative/math/asecpi.cpp"                )
generate_test("unit/module/derivative/math/asin.cpp"                  )
generate_test("unit/module/derivative/math/asind.cpp"                 )
generate_test("unit/module/derivative/math/asinh.cpp"                 )
generate_test("unit/module/derivative/math/asinpi.cpp"                )
generate_test("unit/module/derivative/math/atan2.cpp"                 )
generate_test("unit/module/derivative/math/atan2d.cpp"                )
generate_test("unit/module/derivative/math/atan2pi.cpp"               )
generate_test("unit/module/derivative/math/atan.cpp"                  )
generate_test("unit/module/derivative/math/atand.cpp"                 )
generate_test("unit/module/derivative/math/atanh.cpp"                 )
generate_test("unit/module/derivative/math/atanpi.cpp"                )
generate_test("unit/module/derivative/math/cbrt.cpp"                  )
generate_test("unit/module/derivative/math/cos.cpp"                   )
generate_test("unit/module/derivative/math/cosd.cpp"                  )
generate_test("unit/module/derivative/math/cosh.cpp"                  )
generate_test("unit/module/derivative/math/cospi.cpp"                 )
generate_test("unit/module/derivative/math/cot.cpp"                   )
generate_test("unit/module/derivative/math/cotd.cpp"                  )
generate_test("unit/module/derivative/math/coth.cpp"                  )
generate_test("unit/module/derivative/math/cotpi.cpp"                 )
generate_test("unit/module/derivative/math/csc.cpp"                   )
generate_test("unit/module/derivative/math/cscd.cpp"                  )
generate_test("unit/module/derivative/math/csch.cpp"                  )
generate_test("unit/module/derivative/math/cscpi.cpp"                 )
generate_test("unit/module/derivative/math/exp10.cpp"                 )
generate_test("unit/module/derivative/math/exp2.cpp"                  )
generate_test("unit/module/derivative/math/exp.cpp"                   )
generate_test("unit/module/derivative/math/expm1.cpp"                 )
generate_test("unit/module/derivative/math/expx2.cpp"                 )
generate_test("unit/module/derivative/math/gd.cpp"                    )
generate_test("unit/module/derivative/math/geommean.cpp"              )
generate_test("unit/module/derivative/math/hypot.cpp"                 )
generate_test("unit/module/derivative/math/invgd.cpp"                 )
generate_test("unit/module/derivative/math/log10.cpp"                 )
generate_test("unit/module/derivative/math/log1p.cpp"                 )
generate_test("unit/module/derivative/math/log2.cpp"                  )
generate_test("unit/module/derivative/math/log_abs.cpp"               )
generate_test("unit/module/derivative/math/log.cpp"                   )
generate_test("unit/module/derivative/math/logspace_add.cpp"          )
generate_test("unit/module/derivative/math/logspace_sub.cpp"          )
generate_test("unit/module/derivative/math/lpnorm.cpp"                )
generate_test("unit/module/derivative/math/nthroot.cpp"               )
generate_test("unit/module/derivative/math/pow1p.cpp"                 )
generate_test("unit/module/derivative/math/pow_abs.cpp"               )
generate_test("unit/module/derivative/math/pow.cpp"                   )
generate_test("unit/module/derivative/math/powm1.cpp"                 )
generate_test("unit/module/derivative/math/sec.cpp"                   )
generate_test("unit/module/derivative/math/secd.cpp"                  )
generate_test("unit/module/derivative/math/sech.cpp"                  )
generate_test("unit/module/derivative/math/secpi.cpp"                 )
generate_test("unit/module/derivative/math/sinc.cpp"                  )
generate_test("unit/module/derivative/math/sincos.cpp"                )
generate_test("unit/module/derivative/math/sin.cpp"                   )
generate_test("unit/module/derivative/math/sindcosd.cpp"              )
generate_test("unit/module/derivative/math/sind.cpp"                  )
generate_test("unit/module/derivative/math/sinhc.cpp"                 )
generate_test("unit/module/derivative/math/sinhcosh.cpp"              )
generate_test("unit/module/derivative/math/sinh.cpp"                  )
generate_test("unit/module/derivative/math/sinpic.cpp"                )
generate_test("unit/module/derivative/math/sinpicospi.cpp"            )
generate_test("unit/module/derivative/math/sinpi.cpp"                 )
generate_test("unit/module/derivative/math/tan.cpp"                   )
generate_test("unit/module/derivative/math/tand.cpp"                  )
generate_test("unit/module/derivative/math/tanh.cpp"                  )
generate_test("unit/module/derivative/math/tanpi.cpp"                 )
##==================================================================================================
## module/derivative/polynomial tests
##==================================================================================================
generate_test("unit/module/derivative/polynomial/gegenbauer.cpp"       )
generate_test("unit/module/derivative/polynomial/hermite.cpp"          )
generate_test("unit/module/derivative/polynomial/horner.cpp"           )
generate_test("unit/module/derivative/polynomial/jacobi.cpp"           )
generate_test("unit/module/derivative/polynomial/laguerre.cpp"         )
generate_test("unit/module/derivative/polynomial/legendre.cpp"         )
generate_test("unit/module/derivative/polynomial/reverse_horner.cpp"   )
generate_test("unit/module/derivative/polynomial/tchebytchev.cpp"      )
##==================================================================================================
## module/derivative/bessel tests
##==================================================================================================
generate_test("unit/module/derivative/bessel/airy_ai.cpp"                )
generate_test("unit/module/derivative/bessel/airy_bi.cpp"                )
generate_test("unit/module/derivative/bessel/cyl_bessel_i0.cpp"          )
generate_test("unit/module/derivative/bessel/cyl_bessel_i1.cpp"          )
generate_test("unit/module/derivative/bessel/cyl_bessel_in.cpp"          )
generate_test("unit/module/derivative/bessel/cyl_bessel_j0.cpp"          )
generate_test("unit/module/derivative/bessel/cyl_bessel_j1.cpp"          )
generate_test("unit/module/derivative/bessel/cyl_bessel_jn.cpp"          )
generate_test("unit/module/derivative/bessel/cyl_bessel_k0.cpp"          )
generate_test("unit/module/derivative/bessel/cyl_bessel_k1.cpp"          )
generate_test("unit/module/derivative/bessel/cyl_bessel_kn.cpp"          )
generate_test("unit/module/derivative/bessel/cyl_bessel_y0.cpp"          )
generate_test("unit/module/derivative/bessel/cyl_bessel_y1.cpp"          )
generate_test("unit/module/derivative/bessel/cyl_bessel_yn.cpp"          )
generate_test("unit/module/derivative/bessel/sph_bessel_j0.cpp"          )
generate_test("unit/module/derivative/bessel/sph_bessel_j1.cpp"          )
generate_test("unit/module/derivative/bessel/sph_bessel_jn.cpp"          )
generate_test("unit/module/derivative/bessel/sph_bessel_y0.cpp"          )
generate_test("unit/module/derivative/bessel/sph_bessel_y1.cpp"          )
generate_test("unit/module/derivative/bessel/sph_bessel_yn.cpp"          )
##==================================================================================================
## module/derivative/special tests
##==================================================================================================
generate_test("unit/module/derivative/special/beta.cpp"                   )
generate_test("unit/module/derivative/special/betainc.cpp"                )
generate_test("unit/module/derivative/special/betainc_inv.cpp"            )
generate_test("unit/module/derivative/special/dawson.cpp"                 )
generate_test("unit/module/derivative/special/erfc.cpp"                   )
generate_test("unit/module/derivative/special/erfc_inv.cpp"               )
generate_test("unit/module/derivative/special/erf.cpp"                    )
generate_test("unit/module/derivative/special/erfcx.cpp"                  )
generate_test("unit/module/derivative/special/erf_inv.cpp"                )
generate_test("unit/module/derivative/special/exp_int.cpp"                )
generate_test("unit/module/derivative/special/gamma_p.cpp"                )
generate_test("unit/module/derivative/special/lambert.cpp"                )
generate_test("unit/module/derivative/special/lbeta.cpp"                  )
generate_test("unit/module/derivative/special/log_gamma.cpp"              )
generate_test("unit/module/derivative/special/lrising_factorial.cpp"      )
generate_test("unit/module/derivative/special/omega.cpp"                  )
generate_test("unit/module/derivative/special/rising_factorial.cpp"       )
generate_test("unit/module/derivative/special/signgam.cpp"                )
generate_test("unit/module/derivative/special/tgamma.cpp"                 )
